#!/usr/bin/env python3
"""LLM-retitle ppf-contact-solver conversation chunks using local Ollama.

Generates a concise, descriptive title (≤12 words) for each chunk by
summarizing its content. Updates the title column and FTS5 in brain.db.

Checkpoint: brain/eval/retitle_ppf_checkpoint.json — safe to interrupt and resume.

Usage:
    python3 brain/tools/retitle_ppf_llm.py [--dry-run] [--batch 50]
"""
from __future__ import annotations

import argparse
import json
import os
import sqlite3
import sys
import time
from pathlib import Path

try:
    import requests
except ImportError:
    sys.exit("pip install requests first")

_REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DB = _REPO_ROOT / "brain" / "rust" / "brain.db"
CHECKPOINT = _REPO_ROOT / "brain" / "eval" / "retitle_ppf_checkpoint.json"

MAX_CONTENT_CHARS = 1200  # truncate long chunks before sending
SLEEP_BETWEEN = 0.4       # seconds between calls


def _llm_title(content: str, key: str = "") -> str:
    snippet = content[:MAX_CONTENT_CHARS]
    prompt = (
        "Generate a concise, descriptive title (≤12 words) for the following technical documentation chunk. "
        "The title should capture the core topic so a developer can find this chunk by searching for it. "
        "Return ONLY the title — no punctuation at the end, no quotes, no explanation.\n\n"
        f"Content:\n{snippet}"
    )
    from brain.core.summarizer import _chat
    # Strip surrounding quotes if the model added them
    title = _chat(prompt, max_tokens=40).strip().strip("\"'")
    # Truncate to 100 chars just in case
    if len(title) > 100:
        title = title[:97] + "..."
    return title


def _sync_fts(conn: sqlite3.Connection, memory_id: str) -> None:
    conn.execute(
        "DELETE FROM memories_fts WHERE rowid=(SELECT rowid FROM memories WHERE id=?)",
        (memory_id,),
    )
    conn.execute(
        "INSERT INTO memories_fts(rowid, id, content, title) "
        "SELECT rowid, id, content, title FROM memories WHERE id=?",
        (memory_id,),
    )


def load_checkpoint() -> set[str]:
    if CHECKPOINT.exists():
        data = json.loads(CHECKPOINT.read_text())
        return set(data.get("done", []))
    return set()


def save_checkpoint(done: set[str]) -> None:
    CHECKPOINT.write_text(json.dumps({"done": sorted(done)}, indent=2))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Show plan, no API calls")
    parser.add_argument("--batch", type=int, default=0, help="Process only N rows (0=all)")
    parser.add_argument("--db", type=Path, default=DEFAULT_DB)
    args = parser.parse_args(argv)

    key = ""  # titles now generated by local Ollama via summarizer._chat; no API key needed

    conn = sqlite3.connect(str(args.db))
    conn.execute("PRAGMA journal_mode=WAL")

    rows = conn.execute(
        "SELECT id, content, title FROM memories "
        "WHERE project='ppf-contact-solver' AND type IN ('\"conversation\"', '\"solution\"') "
        "ORDER BY rowid"
    ).fetchall()
    print(f"Total ppf conversation+solution chunks: {len(rows)}")

    done = load_checkpoint()
    pending = [(mid, content, title) for mid, content, title in rows if mid not in done]
    print(f"Already done: {len(done)}  Remaining: {len(pending)}")

    if args.batch:
        pending = pending[: args.batch]
        print(f"Limiting to {args.batch} rows this run.")

    if args.dry_run:
        print("\n[DRY-RUN] First 3 chunks to retitle:")
        for mid, content, title in pending[:3]:
            print(f"  id={mid[:8]}...")
            print(f"  OLD title: {(title or '')[:80]}")
            print(f"  content[:150]: {(content or '')[:150]}")
            print()
        return 0

    updated = 0
    errors = 0
    for i, (mid, content, old_title) in enumerate(pending, 1):
        try:
            new_title = _llm_title(content or "", key)
        except Exception as e:
            print(f"  [{i}/{len(pending)}] ERROR {mid[:8]}: {e}")
            errors += 1
            continue

        conn.execute("UPDATE memories SET title=? WHERE id=?", (new_title, mid))
        _sync_fts(conn, mid)
        done.add(mid)
        updated += 1

        if i % 10 == 0:
            conn.commit()
            save_checkpoint(done)
            print(f"  [{i}/{len(pending)}] committed. last: {new_title!r}")
        elif i % 50 == 0 or i == len(pending):
            print(f"  [{i}/{len(pending)}] {new_title!r}")

        time.sleep(SLEEP_BETWEEN)

    conn.commit()
    save_checkpoint(done)
    conn.close()
    print(f"\nDone. updated={updated} errors={errors} checkpoint={CHECKPOINT}")
    return 0 if errors == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
